version: '3.8'
services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 512M
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/PHP.Dockerfile
        volumes:
            - ./app:/app
        env_file:
            - .env
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 512M
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:latest
        environment:
            PMA_ARBITRARY: "1"
        ports: 
            - "8080:80"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 512M
    mysql:
        container_name: mysql
        image: mariadb:latest
        env_file: 
            - .env
        volumes:
        - mysqldata:/var/lib/mysql
        - ./docker/init_db:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 512M
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 512M
volumes:
    mysqldata: {}