version: '3.8'
services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/PHP.Dockerfile
        volumes:
            - ./app:/app
        env_file:
            - .env
    mysql:
        container_name: mysql
        image: mariadb:latest
        env_file: 
            - .env
        volumes:
        - mysqldata:/var/lib/mysql
        - ./docker/init.sh:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
volumes:
    mysqldata: {}